config/routes.rb
Dubsar::Application.routes.draw do

  root :to => "home#index"

  # scene
  match "/search" => "home#search", :as => "search"
  match "/find" => "home#find", :as => "find"
  match "/view" => "home#view", :as => "view"
  match "/play" => "home#play", :as => "play"
  match "/read" => "home#read", :as => "read"
  match "/cloud" => "home#cloud", :as => "cloud"
  match "/login" => "sessions#new", :as => "login"
  match "/logout" => "sessions#destroy", :as => "logout"

  # names
  namespace :names do
    root to: "names#home"
    resources :entities
    resources :things
    resources :properties
    resources :links
  end
  
  # matters
  namespace :matters do
    root to: "matters#home"
  end
  Router.matters(self)
  
  # system
  resources :users
  resources :sessions
end

app/models/names/entity.rb
module Names
  class Entity < Name
  end
end

app/models/names/link.rb
module Names
  class Link < Name
  end
end

app/models/names/name.rb
require 'active_support/inflector'
module Names
  class Name < Bala
    before_create :check_name
    attr_accessor :parent, :fields
    attr_accessible :name, :parent, :fields
    self.abstract_class = true
    def self.table_name
      (self.name.split("::").last << "Name").tableize
    end
    def fields=(_fields)
      @fields = []
      JSON.parse(_fields).each do |f|
        @fields << DB::Field.new(f["name"], f["type"])
      end
    end
    def entity?
      self.class.name == "Names::Entity"
    end
    def thing?
      self.class.name == "Names::Thing"
    end
    def matter
      # the name attribute holds the table name
      # of the matter this instance defines
      # this method returns the defined metter's class
      cname = "Matters::"
      cname << "Things" if thing?
      cname << "Entities" if entity?
      cname << "::" << self.name.singularize.camelize
      cname.constantize
    end
    def check_name
      self.name = self.name.tableize
    end
  end
end

app/models/names/property.rb
module Names
  class Property < Name
  end
end

app/models/names/property_link.rb
module Names
  class PropertyLink < Name
  end
end

app/models/names/thing.rb
module Names
  class Thing < Name
  end
end

app/controllers/names/entities_controller.rb
module Names
  class EntitiesController < Names::NamesController
    def index
      respond_with(@names = Names::Entity.all)
    end
    def show
      respond_with(@name = Names::Entity.find(params[:id]))
    end
    def new
      respond_with(@name = Names::Entity.new)
    end
    def create
      @name = create_name(Names::Entity)
      respond_with(@name)
    end
  end
end

app/controllers/names/names_application_controller.rb
module Names
  class NamesApplicationController < ApplicationController
    before_filter :require_login
  end
end

app/controllers/names/names_controller.rb
module Names
  class NamesController < NamesApplicationController
    layout 'home'
    respond_to :html
    def home
    end
    def create_name(klazz)
      name = klazz.new
      Name.transaction do
        case klazz.name
        when /.*Thing/
          name = klazz.create(params["names_thing"])
          parent = klazz.find(name.parent)
          DB.create_thing(name.name, parent.name, name.fields)
        when /.*Entity/
          name = klazz.create(params["names_entity"])
          parent = klazz.find(name.parent)
          DB.create_entity(name.name, parent.name, name.fields)
        end
      end
      name
    end
  end
end

app/controllers/names/property_links_controller.rb
module Names
  class PropertyLinksController < NamesController
  end
end

app/controllers/names/property_names_controller.rb
module Names
  class PropertyNamesController < NamesController
  end
end

app/controllers/names/propertys_controller.rb
module Names
  class PropertyNamesController < NamesController
  end
end

app/controllers/names/things_controller.rb
module Names
  class ThingsController < NamesController
    respond_to :html
    def index
      respond_with(@names = Names::Thing.all.reject {|n| n.name == "things"})
    end
    def show
      respond_with(@name = Names::Thing.find(params[:id]))
    end
    def new
      respond_with(@name = Names::Thing.new)
    end
    def create
      @name = create_name(Names::Thing)
      respond_with(@name)
    end
  end
end

app/views/names/names/home.html.haml
%table
  %tr
    %td= names_forest

app/views/names/names/index.html.haml
%table
  - @names.each do |name|
    %tr
      %td= link_to name.name, polymorphic_path(name)

%table
  %tr
    %td= link_to "Names Home", names_root_path

app/views/names/names/new.html.haml
= simple_form_for @name, :html => {:id => "new_name_form"} do |f|
  = f.input :parent, :collection => @name.class.order(:name), :include_blank => false
  = f.input :name
  = f.hidden_field :fields, :id => "new_name_fields"
  = f.button :submit

%div{:style => "border: 1px black solid;"}
  %div= "Fields"
  %div#fields_list
  %div#field_form_proto
    %input#field_form_name{name: "name"}
    %select#field_form_type
      - %w(String Text Integer Binary).sort.each do |o|
        %option= o
    %button#field_form_submit= "Add Field"

app/views/names/names/show.html.haml
- clazz = @name.matter
%table
  %tr
    %td
      %h3= clazz.name
  - clazz.columns.each do |column|
    %tr
      %td
        %strong= column.name

= link_to "New", polymorphic_path(@name, action: :new)