config/routes.rb
Dubsar::Application.routes.draw do

  root :to => "home#index"

  # scene
  match "/search" => "home#search", :as => "search"
  match "/find" => "home#find", :as => "find"
  match "/view" => "home#view", :as => "view"
  match "/play" => "home#play", :as => "play"
  match "/read" => "home#read", :as => "read"
  match "/cloud" => "home#cloud", :as => "cloud"
  match "/login" => "sessions#new", :as => "login"
  match "/logout" => "sessions#destroy", :as => "logout"

  # names
  namespace :names do
    root to: "names#home"
    resources :entities
    resources :things
    resources :properties
    resources :links
  end
  
  # matters
  namespace :matters do
    root to: "matters#home"
  end
  Router.matters(self)
  
  # system
  resources :users
  resources :sessions
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  #load_and_authorize_resource class: "Matters::Things::Video"
  def index
    # TODO: handle no videos in db
    @video = Matters::Things::YoutubeVideo.random
    @video.autoplay = false
  end
  def search
  end
  def find
    #@search = Search.query(params['q'])
    @search = FullTextSearch.new(params['q']).items
    render :layout => "find"
  end
  def view
    item = Item.new(params);
    if item.clazz < Matters::Things::Video
      @video = item.clazz.find item.id
      render :play
    end
  end
  def play
  end
  def read
  end
  def cloud
    render :json => Search.cloud
  end
  private
  class Item
    def initialize(_params)
      @params = _params
    end
    def clazz
      class_for(@params['item-class'])
    end
    def id
      @params['item-id'] || default_id
    end
    def class_for(_table_name)
      clazz = default_clazz
      begin
        #clazz = _table_name.singularize.camelize.constantize
        clazz = _table_name.constantize
      rescue Exception => e
        logger.debug e
      end
    end
    def default_clazz
      Matters::Things::YoutubeVideo
    end
    def default_id
      Matters::Things::YoutubeVideo.random.id
    end
  end
end

app/views/home/find.html.haml
%ul.items
  - if @search.count == 0
    %li= "... oops .. nothing found"
  - else
    - @search.each do |item|
      %li.item{:data => {:"d-item-class" => item.item_relation, :"d-item-id" => item.item_id}}= item.description

= form_tag view_path, :id => "view", :method => :get do
  %input#item-id(type="hidden" name="item-id")
  %input#item-class(type="hidden" name="item-class")

app/views/home/index.html.haml
%table.dashboard
  %tr
    %td= render "youtube_player"

app/views/home/play.html.haml
%table.dashboard
  %tr
    %td= render "youtube_player"

app/views/home/search.html.haml
%table
  %tr
    %td.cloud
      #cloud
      #search
        %form{:action => "/find"}
          %input#search-dubsar{:name => "q"}